package store

import (
	"database/sql"
	"log"

	//postgres ...
	_ "github.com/lib/pq"
)

//ConnStr ...
var ConnStr string = "user=postgres password=123 dbname=images_db sslmode=disable"

//CreateDB ...
func CreateDB() *sql.DB {
	var db *sql.DB

	db, err := sql.Open("postgres", ConnStr)
	if err != nil {
		log.Print(err)
	}

	return db
}

//CreateTable ...
func CreateTable(db *sql.DB) {
	db.Exec("delete  from img_url_color")

	_, err := db.Exec("create table if not exists " +
		`img_url_color("id" integer primary key generated by default as identity,` +
		`"url_name" varchar(100), "color" varchar(25))`)
	if err != nil {
		log.Print(err)
	} else {
		log.Println("Table created...")
	}
}
